### ISSUE TITLE
Translate with 2 arguments

### ISSUE THREAD

**Issue by laminr** [nylo-core/framework#30]
Hello,

I have this translation: `"backup.restore.label": "{{acNb}} aircraft(s) and {{flNb}} flight(s) restored"`
when I call:
`"backup.restore.label".tr(arguments: {"acNb": aircraftNb.toString(), "flNb": flightsNb.toString()},)`

The `acNb` value is never set, but the `flNb` is.
I see for instance: "{{acNb}} aircraft(s) and 10 flight(s) restored"

**Comment by agordn52** [comment]
Hey @laminr, thanks for spotting this. I'll take a look.

**Comment by agordn52** [comment]
Hi @laminr, this is resolved now.
Update your pubspec.yaml to now use `nylo_framework: ^2.2.0` 👍

**Comment by laminr** [comment]
So cool! Thanks
