### ISSUE TITLE
Future<T?> network<T>

### ISSUE THREAD

**Issue by lacoste-sochi** [nylo-core/framework#31]
Greetings, why not return an error instead of null?

When I call an api method from a page, I would like to see the response in order to process it further.

Those answers that I don't want to process individually, the global displayError will do fine.

![image](https://user-images.githubusercontent.com/42961050/172797731-7c99e9e2-2527-488a-9108-f2b8b2c564d2.png)

**Comment by agordn52** [comment]
Hi @lacoste-sochi,

Thanks for the comment.

The `network` helper is still returning the error from the try and catch (line 68 and 73).
In your API Service, you can handle the response.

I've noticed that the try and catch `Exception` block is missing the `onError` callback so I'll create a PR for that.

**Comment by lacoste-sochi** [comment]
> Hi @lacoste-sochi,
> 
> Thanks for the comment.
> 
> The `network` helper is still returning the error from the try and catch (line 68 and 73). In your API Service, you can handle the response.
> 
> I've noticed that the try and catch `Exception` block is missing the `onError` callback so I'll create a PR for that.



The fact is that `handleFailure `is useless. DIO error is triggered at the stage

`Response response = await request(_api);`

It turns out that handleFailure does not work at all, for an error like

`Http status error [400]`


For example, I need to output errors and buttons for this method to alert, message. I can't assign globally, I have different event reversals

**Comment by agordn52** [comment]
I'll look into this at my earliest convenience.

**Comment by agordn52** [comment]
@lacoste-sochi, thanks for spotting this.

It's been fixed in **v3.1.4** 🚀
https://pub.dev/packages/nylo_framework
