### ISSUE TITLE
Need to upgrade theme_provider

### ISSUE THREAD

**Issue by saputro-dwy** [nylo-core/framework#33]
Hi, iam newbie and Nylo Framework is use full as best practice for me.
i have some problem while compile. in short, it looks like it needs to upgrade theme_provider version.
Now i use 'dependency_overrides' to fix it.
thank you so much.

**Comment by agordn52** [comment]
Hi @saputro-dwy, 

Thanks for reporting this. We're aware it's with Flutter v3.10.0.
An update will be out soon.

**Comment by agordn52** [comment]
Hi @saputro-dwy,

v5.0.0 is now out 🚀

However, if you're coming from Nylo 4.x or lower, check out the changes in this commit: https://github.com/nylo-core/nylo/commit/b15b3b8f9677a975290cfb397c71a554307f5993#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25

You'll need to update the following packages to use Flutter v3.10.0
- intl: ^0.18.0
- nylo_framework: 4.2.0

If you're building a new project, check out v5.0.0 https://nylo.dev

Thanks,
Anthony
