### ISSUE TITLE
is there a possibility that nylo supports web platforms?

### ISSUE THREAD

**Issue by teoprayoga** [nylo-core/framework#34]

**Comment by agordn52** [comment]
Hi @teoprayoga, Nylo can be used to build Flutter websites if that's what you are asking.
Hope that helps 👍

**Comment by teoprayoga** [comment]
how to build nylo web release?
I run fvm flutter build web --release. it says missing index.html

**Comment by agordn52** [comment]
Hi @teoprayoga,
Yeah, you'll need to include an index.html file.
