### ISSUE TITLE
AuthRouteGuard Not Triggered on Specified Route

### ISSUE THREAD

**Issue by lepresk** [nylo-core/framework#36]
I'm encountering an issue while attempting to implement authentication functionality in my app. The `AuthRouteGuard` doesn't seem to be triggered after adding it to a specific route as shown below:

```
router.route(LoginPage.path, (context) => LoginPage(), authPage: true);
router
      .route(HomePage.path, (context) => HomePage(), initialRoute: true)
      .addRouteGuard(AuthRouteGuard());
```

Despite adding `authPage: true` to the LoginPage route, it has no effect, and the HomePage is still opening first. Is there something wrong with my implementation?

**Comment by agordn52** [comment]
Hi @lepresk,

Hope you're well.
Thanks for sharing the code snippet, I think your code should be like this instead.

``` dart 
router.route(LoginPage.path, (context) => LoginPage(), initialRoute: true);

router.route(HomePage.path, (context) => HomePage(), authPage: true)
      .addRouteGuard(AuthRouteGuard());
```

I'm assuming that you don't want unauthenticated users to not have access to the 'HomePage'.

After the user is logged into your application, you can call e.g.
``` dart
User user = User(); // example user model

await Auth.set(user); // login user
```

The next time the user opens the app, the initial page will be `HomePage` because they are logged in, hope that helps 👍

Lastly re. route guards
In your project, use the `routeTo` helper for navigation because this will perform the check on any route guards before routing.

Thanks,

**Comment by lepresk** [comment]
Thank you, @agordn52, for your prompt response. It's working now. However, if I have multiple protected routes, should I only use `.addRouteGuard(AuthRouteGuard())`, or should I also specify `authPage: true`?

**Comment by agordn52** [comment]
No problem, @lepresk

If you need to protect multiple routes, you can add the route guard on all the routes required.
The `authPage` only tells Nylo which page should be loaded as the initial page if the `User` is authenticated.
 
In the future, I plan to allow developers to group routes like in Laravel.

Something like this would be nice, I'll experiment with some ideas over the weekend.
``` dart
appRouter() => nyRoutes((router) {

router.group(() => {
            "route_guards": [AuthRouteGuard()] // example
      }, (router) {
  router.router(AccountPage.path, (context) => AccountPage());

  router.router(DashboardPage.path, (context) => DashboardPage());
});

```

**Comment by agordn52** [comment]
@lepresk,

It's now possible to do this in your router, you'll just need to update nylo_framework to [5.21.10](https://pub.dev/packages/nylo_framework)

``` dart
appRouter() => nyRoutes((router) {
...
router.group(() => {
    "route_guards": [AuthRouteGuard()],
    "prefix": "/dashboard"
  }, (router) {
    router.route(AccountPage.path, (context) => AccountPage());

    router.route(DashboardPage.path, (context) => DashboardPage());
  }); 
```

**Comment by lepresk** [comment]
I'm thrilled about this change, which will significantly streamline the process. However, what still concerns me is that `route.group` parmareters is not type-safe
