### ISSUE TITLE
[BUG] Model generator with json argument does not complete

### ISSUE THREAD

**Issue by A0x1E** [nylo-core/framework#38]
When I run `dart run nylo_framework:main make:model post --json` the CLI doesn't respond to Ctrl + D command. The launch was carried out on Windows 11 in cmd and pwsh (v. 7.4.2) with no results. Ctrl + C command works properly.

![Screenshoot](https://github.com/nylo-core/framework/assets/48892056/dab9e6d2-0632-4d0e-be51-152459bf2640)

**Comment by agordn52** [comment]
Hi @A0x1E,

Thanks for reporting this, I've pushed an update [v5.25.3](https://pub.dev/packages/nylo_framework) for **nylo_framework**.

It will now check the OS and provide `Ctrl + C` for Windows 👍
