### ISSUE TITLE
Could anyone provide a elegant example for this potential framework ?

### ISSUE THREAD

**Issue by loveoverflowdev** [nylo-core/framework#39]
I saw no examples that use this framework in example folder:

![image](https://github.com/nylo-core/framework/assets/113291130/892b38b5-a278-4d20-ad72-e077673ee9de)

**Comment by agordn52** [comment]
Hi @loveoverflowdev,

Use the nylo repo to build a project as mentioned in the README.

<img width="820" alt="Screenshot 2024-07-05 at 14 19 40" src="https://github.com/nylo-core/framework/assets/17294994/b847db66-3d5c-4b0b-8374-b1a2a9a18d81">

Hope that helps.

**Comment by loveoverflowdev** [comment]
Thank you, have a nice day
