### ISSUE TITLE
Make Storable Immutable

### ISSUE THREAD

**Issue by TheGreyBurger** [nylo-core/framework#4]
Hi,

Does it make sense to make Storable object immutable compatible ?
- Create CONST constructor in class Storable
- Make fromStorage return <dynamic> as it return a new filled object

Thanks,

NB : Thanks for your work :) I hope i can contribute to it !

**Comment by agordn52** [comment]
Hi,

That could work. I'd be happy to give you talk around the framework and take a deeper dive into things.
There's a lot of cool ideas and things we could try.

You can reach out through Twitter or agordon@nylo.dev and we can arrange a talk.
Thanks, Anthony
