### ISSUE TITLE
The method 'isBefore' isn't defined for the class 'TimeOfDay'.

### ISSUE THREAD

**Issue by Ashik55** [nylo-core/framework#41]
Error (Xcode): ../../.pub-cache/hosted/pub.dev/date_field-5.3.4/lib/src/widgets/adaptive_dialog.dart:47:11: Error: The method 'isBefore' isn't defined for the class 'TimeOfDay'.

After pulling : git clone https://github.com/nylo-core/nylo.git, its throwing Error: The method 'isBefore' isn't defined for the class 'TimeOfDay'. for xcode build.

**Comment by Ashik55** [comment]
Android Build also failed

Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
../../.pub-cache/hosted/pub.dev/date_field-5.3.4/lib/src/widgets/adaptive_dialog.dart:47:11: Error: The method 'isBefore' isn't defined for the class 'TimeOfDay'.
 - 'TimeOfDay' is from 'package:flutter/src/material/time.dart' ('../../flutter/packages/flutter/lib/src/material/time.dart').
Try correcting the name to the name of an existing method, or defining a method named 'isBefore'.
  if (now.isBefore(TimeOfDay.fromDateTime(firstDate))) {
          ^^^^^^^^
../../.pub-cache/hosted/pub.dev/date_field-5.3.4/lib/src/widgets/adaptive_dialog.dart:51:11: Error: The method 'isAfter' isn't defined for the class 'TimeOfDay'.
 - 'TimeOfDay' is from 'package:flutter/src/material/time.dart' ('../../flutter/packages/flutter/lib/src/material/time.dart').
Try correcting the name to the name of an existing method, or defining a method named 'isAfter'.
  if (now.isAfter(TimeOfDay.fromDateTime(lastDate))) {
          ^^^^^^^
Target kernel_snapshot_program failed: Exception


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/aashiq/flutter/bin/flutter'' finished with non-zero exit value 1

**Comment by agordn52** [comment]
Hi @Ashik55,

Looks like an issue with the [date_field](https://pub.dev/packages/date_field/changelog) package used in the framework.
I've updated it to `^6.0.0` to resolve the issue as per their changelog.

Update your project to use `nylo_framework: ^6.4.3`
